import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback, useEffect, useState } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";

/** Estimate English voiceover duration at roughly 155 words per minute. */
function estimateMs(text: string): number {
  if (!text) return 1500;
  const words = text.trim().split(/\s+/).filter(Boolean).length;
  return Math.max(1500, Math.round((words / 155) * 60_000));
}

export default function App() {
  const stepper = useStepper(CHAPTERS);
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";
  const renderMode =
    typeof window !== "undefined" &&
    new URLSearchParams(window.location.search).get("render") === "1";
  const [renderStarted, setRenderStarted] = useState(!renderMode);
  const [renderEpoch, setRenderEpoch] = useState(0);

  useEffect(() => {
    if (!renderMode) return;
    const start = () => {
      setRenderEpoch((value) => value + 1);
      setRenderStarted(true);
    };
    window.addEventListener("levelfield-render-start", start, { once: true });
    return () => window.removeEventListener("levelfield-render-start", start);
  }, [renderMode]);

  const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  // (1-indexed file names match what `extract-narrations.ts` outputs.)
  // Empty narration → no audio src, Auto mode falls back to estimate.
  const audioSrc =
    mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  useAudioPlayer({
    src: audioSrc,
    // The offline renderer owns the exact, ffprobe-derived timeline and
    // advances the deck itself. Keeping browser audio out of that path makes
    // capture deterministic even when headless Chromium has no audio sink.
    mode: renderMode ? "manual" : mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted: renderMode || autoStarted,
  });

  return (
    <>
      <Stage onAdvance={stepper.next}>
        <div
          key={`${ch.id}-${stepper.cursor.step}-${mode === "auto" && !autoStarted && !renderMode ? "gated" : "active"}-${renderEpoch}`}
          className="scene"
          data-chapter={ch.id}
          data-step={stepper.cursor.step}
        >
          <Cmp step={stepper.cursor.step} />
        </div>
      </Stage>
      <ProgressBar
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
        githubUrl={null}
      />
      <AutoToggle mode={mode} onCycle={cycleMode} />
      <AutoStartGate
        visible={mode === "auto" && !autoStarted && !renderMode}
        onStart={() => setAutoStarted(true)}
      />
      {renderMode && !renderStarted ? (
        <div
          className="render-calibration"
          aria-hidden="true"
          style={{
            position: "fixed",
            inset: 0,
            zIndex: 10000,
            background: "#ff00ff",
          }}
        />
      ) : null}
    </>
  );
}
